### ISSUE TITLE
Tasks have issues rolling over

### ISSUE THREAD

**Issue by metkucmanic** [jamiefdhurst/obsidian-auto-tasks#20]
I love the idea of this plugin. I have been having some issues that I have been able to troubleshoot, but not completely resolve. 

1. Tasks were not rolling over: I figured out that you need to use tasks in emoji format and not dataview format for them to rollover, otherwise, they do not rollover. 
-  (I am not the biggest fan of the emoji format since I find all the emojis too distracting)
2. The heading that tasks go under does not go under an existing header, but creates a new one. Ideally, was expecting the rolled over tasks to go under an existing header in my daily note template
3. FYI: If you use dataview to show tasks globally and the kanban board, it will duplicate all tasks

Ideal features: 
I currently use the rollover daily todos plugin to move my tasks from the previous note. I then will use the Task Collector (TC) plugin to globally add a > to all tasks that have been migrated and append a link to the date that they have been migrated so that yesterday's tasks look like - [>] Plan Week [[2024-12-02]]. Having this feature implemented daily would be a dream, especially if I could have this done week to week. 

My Workflow for context: 
Overall, I see this plugin dramatically streamlining my workflow. I have developed my own way of bullet journaling in Obsidian, and am always on the lookout to find ways to migrate tasks while keeping some record of when they were created. I also try to keep some of the analog aspects of bullet journaling in my obsidian vault. 

Personally, I do like the idea of the task plugin but I find the emojis too distracting/ overwhelming (as mentioned earlier) and find dataview to be a better way to organize upcoming and prioritized tasks. I also use tags with emoji colored balls as a way to assign priority as I use a modification of the priority tables in the CBT book, [Mastering Your Adult ADHD](https://www.amazon.com/Mastering-Your-Adult-ADHD-Cognitive-Behavioral/dp/019023556X).  As such, I have migration rules for myself about tasks that need to be done and those that sit in the my weekly notes and daily notes. Oftentimes, these are repeated (which is less of an issue for me), but I like the idea of being able to have all the tasks in my previous daily note (whether they fall under my Plan or throughout the day) and get migrated to the Plan of the next day. I then feel more able to assess the previous day's tasks and decide if I want to postpone tasks by migrating them to my weekly note, doing them on the current day, or reducing their priority so that they sit at the bottom of my priority list. Usually the case is the latter. 

Overall, like I said, I love the idea of this plugin and have found your other plugin Auto Periodic Notes very useful and inline with my current workflow (why I went into such detail...)

**Comment by jamiefdhurst** [comment]
Hi @metkucmanic - firstly thank you for providing so much detail! This is extremely helpful, and will make it much easier for me to work through this, and thank you for your kind words on Auto Periodic Notes too.

As there are a few elements here, I've split the issue up into the following:

- #21 
- #22
- #23
- #24

I will keep this overarching issue as a question and only mark this as complete when the above sub-tasks have been resolved.

Of course - if you're so inclined, please feel free to pick up any of these open tickets and submit a PR before I get to them.

**Comment by metkucmanic** [comment]
Great!! If helpful, I can add more context to the tickets (e.g. my dataview code for pulling tasks).

**Comment by arkag** [comment]
I'm not 100% sure this should be a separate thing, so I'm going to post here and see if anyone else has noticed/agrees with this.

I've been working on streamlining my workflow day to day with work tasks. One of the issues I run into is that I'm not too keen on putting a ton of info into a task or note since I end up having to copy that information into Jira for work, and I don't necessarily want to have to reformat everything (or reduce my verbosity for others) in order to copy that into Jira.

What I've settled on is using the [Jira Issue](https://github.com/marc0l92/obsidian-jira-issue) Plugin alongside the plugins recommended by your plugin here. I believe this has been very helpful in keeping notes alongside tasks, but I am running into issues right now with how the tasks are rolled over. Below will have some markdown and how I'd expect it to roll over vs what is currently happening.

---

## Yesterdays Tasks/Notes

```
## TODOs

- [x] JIRA:TSK-1234 ✅ 2025-06-10
	- [x] Figure out where `server-name-1` is ✅ 2025-06-10
		- John said F2U36-37
		- It's actually F2U39-38
	- [x] Install drives ✅ 2025-06-10
	- [x] Update racktables ✅ 2025-06-10
		- Not sure which one is even the right one to update...
- [/] JIRA:TSK-1235
	- [x] Check with John regarding this ✅ 2025-06-10
	- [n] John is running a scrub and reinstall on the machine, apparently a stick install is supposed to wipe out the IPMI configuration, but it didn't
	- [ ] Check with John for commands used to scrub
	- [x] Update ticket ✅ 2025-06-10
- [/] JIRA:TSK-1236
	- [x] Figure out how to get a bootable USB made for EXA Scaler ✅ 2025-06-10
		- [n] Literally just use Rufus or Balena
	- [x] Create ticket for getting USB plugged into `server-name-2` ✅ 2025-06-10
- [/] JIRA:TSK-1237
	- [n] [[John Doe]] is working with Logistics today to get it shipped  
	- [x] Update ticket ✅ 2025-06-10
- [/] JIRA:TSK-1238
	- [x] Check OS to see what the IPMI IPs are ✅ 2025-06-10
		- [n] they're correct
	- [x] Check physical cables ✅ 2025-06-10
	- [x] Update ticket ✅ 2025-06-10
- [x] 10.12.34.56 no-carrier issue for HSN ✅ 2025-06-10
	- [n] part of the issue was an un-configured port
- [x] Move 4 boxes to shipping area ✅ 2025-06-10
	- [n] Supposed to have gone to other location, they never shipped it

- [i] (topic:: HSN) HSN
	- High Speed networking

- [-] JIRA:TSK-1239
	- [-] Turn it on 
		- Nevermind, he did it via IPMI himself
```

## Expected Today

```
## TODOs

- [/] JIRA:TSK-1235
	- [ ] Check with John for commands used to scrub
- [/] JIRA:TSK-1236
- [/] JIRA:TSK-1237
- [/] JIRA:TSK-1238
```

## Actual Today
```
## TODOs
```

---

So, hopefully what you can see here is that tasks that are not necessarily marked as done are not being carried over, but I believe it'll be more complicated than just carrying over everything that isn't an [x] because I don't necessarily want [n] carried over because it's not necessarily relevant to today's tasks associated with a Jira ticket.

The other issue I'm seeing is that sub-tasks aren't being brought over at all.

**Comment by jamiefdhurst** [comment]
@arkag I will create another issue for the sub-tasks, and use your example test above (thank you!) to ensure I can fix this for you.

**Comment by AzureKitsune** [comment]
I don't know if this helps but I've been using this plugin in combination with your [Auto Periodic Notes](https://github.com/jamiefdhurst/obsidian-auto-periodic-notes) plugin and have been running into the issue of tasks not rolling back as well.

I've found this plugin called [Plugin Manager](https://github.com/ohm-en/obsidian-plugin-manager) which allows you to set a delay on plugins' initialization.

By setting a 5 second delay on Auto Tasks and a 20 second delay on Auto Periodic Notes, its been consistently generating daily notes with my recurring tasks.

**Comment by jamiefdhurst** [comment]
Thinking about this more, if there is a loading issue here, then the best way to ensure this works would be to have a load event in both plugins, and to be able to trigger a delayed load (especially in auto-periodic-notes) if it detects there is an Auto Tasks plugin enabled. I'd rather not put in arbitrary delays, given that although that would solve it, the experience for everyone who isn't using both plugins together would be diminished.
